-- migration.sql

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) DEFAULT '',
    uid VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(100),
    pass TEXT NOT NULL,
    is_verified BOOLEAN DEFAULT 'false',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appauth (
    id SERIAL PRIMARY KEY,
    appid VARCHAR(32) UNIQUE NOT NULL,
    client_id UUID UNIQUE NOT NULL,
    client_secret TEXT UNIQUE NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_access_token (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(32) NOT NULL,
    appid VARCHAR(32) UNIQUE NOT NULL,
    client_id UUID UNIQUE NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS apps (
    id SERIAL PRIMARY KEY,
    appname VARCHAR(100) NOT NULL,
    uid VARCHAR(32) NOT NULL,
    appid VARCHAR(32) UNIQUE NOT NULL,
    homepage VARCHAR(200) NOT NULL,
    origin VARCHAR(200) NOT NULL,
    redirect VARCHAR(200) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_id_token (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(32) NOT NULL,
    appid VARCHAR(32) UNIQUE NOT NULL,
    client_id UUID UNIQUE NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraints
ALTER TABLE appauth ADD FOREIGN KEY (appid) REFERENCES apps(appid);
ALTER TABLE user_access_token ADD FOREIGN KEY (appid) REFERENCES apps(appid);
ALTER TABLE apps ADD FOREIGN KEY (uid) REFERENCES users(uid);
ALTER TABLE user_id_token ADD FOREIGN KEY (appid) REFERENCES apps(appid);

